### ISSUE TITLE
Handle is closed exception during flush

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache-cta#11]
```
04 Jan 2022 11:36:58 [nioEventLoopGroup-3-8] [] Opening /osmcache/dcache/dcache-tpm103/data/0000F3B008DCC88C45028E0CDDA9A5ED004B for reading.
04 Jan 2022 11:37:26 [nioEventLoopGroup-3-8] [] xrootd server error while processing org.dcache.xrootd.protocol.messages.CloseRequest@362106c3 (please report this to support@dcache.org)java.lang.IllegalStateException: Handle is closed
	at org.dcache.pool.repository.v5.ReadHandleImpl.getReplicaFile(ReadHandleImpl.java:102)
	at org.dcache.pool.nearline.NearlineStorageHandler$FlushRequestImpl.getReplicaUri(NearlineStorageHandler.java:969)
	at org.dcache.nearline.cta.ForwardingFlushRequest.getReplicaUri(ForwardingFlushRequest.java:26)
	at org.dcache.nearline.cta.xrootd.DataServerHandler.getFile(DataServerHandler.java:490)
	at org.dcache.nearline.cta.xrootd.DataServerHandler.doOnClose(DataServerHandler.java:333)
	at org.dcache.nearline.cta.xrootd.DataServerHandler.doOnClose(DataServerHandler.java:84)
	at org.dcache.xrootd.core.XrootdRequestHandler.requestReceived(XrootdRequestHandler.java:186)
	at org.dcache.xrootd.core.XrootdRequestHandler.channelRead(XrootdRequestHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.dcache.xrootd.core.XrootdAuthenticationHandler.channelRead(XrootdAuthenticationHandler.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mcmilk** [comment]
Do you know if this issue is fixed?
